// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package chatdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BotUsageDaily struct {
	SubjectKey   string             `json:"subject_key"`
	UsageDate    pgtype.Date        `json:"usage_date"`
	MessageCount int32              `json:"message_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Conversation struct {
	ID                 string             `json:"id"`
	Type               string             `json:"type"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	OwnerGuestKey      *string            `json:"owner_guest_key"`
	ShopID             pgtype.UUID        `json:"shop_id"`
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	LastMessagePreview *string            `json:"last_message_preview"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID                  string             `json:"id"`
	ConversationID      string             `json:"conversation_id"`
	SenderParticipantID string             `json:"sender_participant_id"`
	Body                string             `json:"body"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Participant struct {
	ID             string             `json:"id"`
	ConversationID string             `json:"conversation_id"`
	Role           string             `json:"role"`
	UserID         pgtype.UUID        `json:"user_id"`
	GuestKey       *string            `json:"guest_key"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
