// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package chatdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO participant (id, conversation_id, role, user_id, guest_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, conversation_id, role, user_id, guest_key, last_read_at, created_at
`

type AddParticipantParams struct {
	ID             string      `json:"id"`
	ConversationID string      `json:"conversation_id"`
	Role           string      `json:"role"`
	UserID         pgtype.UUID `json:"user_id"`
	GuestKey       *string     `json:"guest_key"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, addParticipant,
		arg.ID,
		arg.ConversationID,
		arg.Role,
		arg.UserID,
		arg.GuestKey,
	)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.UserID,
		&i.GuestKey,
		&i.LastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const countUnread = `-- name: CountUnread :one
SELECT count(*) AS unread
FROM message
WHERE conversation_id = $1
  AND sender_participant_id <> $2
  AND created_at > COALESCE($3::timestamptz, '-infinity'::timestamptz)
`

type CountUnreadParams struct {
	ConversationID      string             `json:"conversation_id"`
	ViewerParticipantID string             `json:"viewer_participant_id"`
	LastReadAt          pgtype.Timestamptz `json:"last_read_at"`
}

// Tin cua chinh minh khong tinh la chua doc. last_read_at NULL = chua doc gi bao gio.
func (q *Queries) CountUnread(ctx context.Context, arg CountUnreadParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, arg.ConversationID, arg.ViewerParticipantID, arg.LastReadAt)
	var unread int64
	err := row.Scan(&unread)
	return unread, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversation (id, type, owner_user_id, owner_guest_key, shop_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, type, owner_user_id, owner_guest_key, shop_id, last_message_at, last_message_preview, created_at
`

type CreateConversationParams struct {
	ID            string      `json:"id"`
	Type          string      `json:"type"`
	OwnerUserID   pgtype.UUID `json:"owner_user_id"`
	OwnerGuestKey *string     `json:"owner_guest_key"`
	ShopID        pgtype.UUID `json:"shop_id"`
}

// ON CONFLICT DO NOTHING: khi hai tab cung mo hoi thoai, request thua khong tao them
// dong nao va nhan ve 0 row (pgx.ErrNoRows). Caller SELECT bu de lay dung hoi thoai da
// ton tai. Khong dung DO UPDATE gia chi de luon co RETURNING: moi lan mo lai hoi thoai
// cu se sinh mot dead tuple.
func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.ID,
		arg.Type,
		arg.OwnerUserID,
		arg.OwnerGuestKey,
		arg.ShopID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.OwnerGuestKey,
		&i.ShopID,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.CreatedAt,
	)
	return i, err
}

const getBotConversationByGuest = `-- name: GetBotConversationByGuest :one
SELECT id, type, owner_user_id, owner_guest_key, shop_id, last_message_at, last_message_preview, created_at FROM conversation
WHERE type = 'bot' AND owner_guest_key = $1
`

func (q *Queries) GetBotConversationByGuest(ctx context.Context, ownerGuestKey *string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getBotConversationByGuest, ownerGuestKey)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.OwnerGuestKey,
		&i.ShopID,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.CreatedAt,
	)
	return i, err
}

const getBotConversationByUser = `-- name: GetBotConversationByUser :one
SELECT id, type, owner_user_id, owner_guest_key, shop_id, last_message_at, last_message_preview, created_at FROM conversation
WHERE type = 'bot' AND owner_user_id = $1
`

func (q *Queries) GetBotConversationByUser(ctx context.Context, ownerUserID pgtype.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getBotConversationByUser, ownerUserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.OwnerGuestKey,
		&i.ShopID,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.CreatedAt,
	)
	return i, err
}

const getBotUsage = `-- name: GetBotUsage :one
SELECT message_count FROM bot_usage_daily
WHERE subject_key = $1 AND usage_date = $2
`

type GetBotUsageParams struct {
	SubjectKey string      `json:"subject_key"`
	UsageDate  pgtype.Date `json:"usage_date"`
}

// Chi de doc/hien thi (vd bao "con 2 luot"), KHONG dung lam cong tac kiem quota.
func (q *Queries) GetBotUsage(ctx context.Context, arg GetBotUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, getBotUsage, arg.SubjectKey, arg.UsageDate)
	var message_count int32
	err := row.Scan(&message_count)
	return message_count, err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, type, owner_user_id, owner_guest_key, shop_id, last_message_at, last_message_preview, created_at FROM conversation WHERE id = $1
`

// Dung cho phan quyen doc: lay hoi thoai roi moi doi chieu voi nguoi goi. Tach khoi
// GetDirectConversation vi o day chua biet nguoi goi la buyer hay seller, nen chua co
// owner_user_id de loc.
func (q *Queries) GetConversationByID(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.OwnerGuestKey,
		&i.ShopID,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectConversation = `-- name: GetDirectConversation :one
SELECT id, type, owner_user_id, owner_guest_key, shop_id, last_message_at, last_message_preview, created_at FROM conversation
WHERE type = 'direct' AND owner_user_id = $1 AND shop_id = $2
`

type GetDirectConversationParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	ShopID      pgtype.UUID `json:"shop_id"`
}

func (q *Queries) GetDirectConversation(ctx context.Context, arg GetDirectConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getDirectConversation, arg.OwnerUserID, arg.ShopID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.OwnerUserID,
		&i.OwnerGuestKey,
		&i.ShopID,
		&i.LastMessageAt,
		&i.LastMessagePreview,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByRole = `-- name: GetParticipantByRole :one
SELECT id, conversation_id, role, user_id, guest_key, last_read_at, created_at FROM participant
WHERE conversation_id = $1 AND role = $2
LIMIT 1
`

type GetParticipantByRoleParams struct {
	ConversationID string `json:"conversation_id"`
	Role           string `json:"role"`
}

// Dung de lay participant 'bot' cua mot hoi thoai (moi hoi thoai bot co dung mot).
func (q *Queries) GetParticipantByRole(ctx context.Context, arg GetParticipantByRoleParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByRole, arg.ConversationID, arg.Role)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.UserID,
		&i.GuestKey,
		&i.LastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getParticipantByUser = `-- name: GetParticipantByUser :one
SELECT id, conversation_id, role, user_id, guest_key, last_read_at, created_at FROM participant
WHERE conversation_id = $1 AND user_id = $2
`

type GetParticipantByUserParams struct {
	ConversationID string      `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetParticipantByUser(ctx context.Context, arg GetParticipantByUserParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipantByUser, arg.ConversationID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.UserID,
		&i.GuestKey,
		&i.LastReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementBotUsage = `-- name: IncrementBotUsage :one
INSERT INTO bot_usage_daily (subject_key, usage_date, message_count)
VALUES ($1, $2, 1)
ON CONFLICT (subject_key, usage_date)
DO UPDATE SET message_count = bot_usage_daily.message_count + 1, updated_at = now()
RETURNING message_count
`

type IncrementBotUsageParams struct {
	SubjectKey string      `json:"subject_key"`
	UsageDate  pgtype.Date `json:"usage_date"`
}

// TANG-ROI-SO-SANH, khong phai doc-roi-kiem: hai request cung doc 4/5 roi cung ghi 5 se
// cho dung 6 luot. Upsert nay la MOT round-trip nguyen tu, tra ve so luot SAU khi tang —
// caller chi viec so voi han muc.
func (q *Queries) IncrementBotUsage(ctx context.Context, arg IncrementBotUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementBotUsage, arg.SubjectKey, arg.UsageDate)
	var message_count int32
	err := row.Scan(&message_count)
	return message_count, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO message (id, conversation_id, sender_participant_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_participant_id, body, created_at
`

type InsertMessageParams struct {
	ID                  string `json:"id"`
	ConversationID      string `json:"conversation_id"`
	SenderParticipantID string `json:"sender_participant_id"`
	Body                string `json:"body"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ConversationID,
		arg.SenderParticipantID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderParticipantID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationsForShop = `-- name: ListConversationsForShop :many
SELECT c.id, c.type, c.owner_user_id, c.owner_guest_key, c.shop_id, c.last_message_at, c.last_message_preview, c.created_at, unread.total AS unread_total
FROM conversation c
LEFT JOIN participant p
    ON p.conversation_id = c.id AND p.user_id = $1
LEFT JOIN LATERAL (
    SELECT count(*) AS total
    FROM message m
    WHERE m.conversation_id = c.id
      AND m.sender_participant_id IS DISTINCT FROM p.id
      AND m.created_at > COALESCE(p.last_read_at, '-infinity'::timestamptz)
) unread ON TRUE
WHERE c.type = 'direct' AND c.shop_id = $2
ORDER BY c.last_message_at DESC NULLS LAST
LIMIT $3
`

type ListConversationsForShopParams struct {
	ViewerUserID pgtype.UUID `json:"viewer_user_id"`
	ShopID       pgtype.UUID `json:"shop_id"`
	PageLimit    int32       `json:"page_limit"`
}

type ListConversationsForShopRow struct {
	Conversation Conversation `json:"conversation"`
	UnreadTotal  int64        `json:"unread_total"`
}

// Inbox cua seller: truy hoi thoai theo shop_id chu KHONG qua participant, vi luc buyer mo
// hoi thoai thi chat-service chua biet user_id cua seller.
//
// Nhung so chua doc thi van phai qua participant, va do la mot join KHAC: seller chua tra
// loi lan nao thi khong co row nao, va ca hoi thoai dem la chua doc.
func (q *Queries) ListConversationsForShop(ctx context.Context, arg ListConversationsForShopParams) ([]ListConversationsForShopRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForShop, arg.ViewerUserID, arg.ShopID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForShopRow
	for rows.Next() {
		var i ListConversationsForShopRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.Type,
			&i.Conversation.OwnerUserID,
			&i.Conversation.OwnerGuestKey,
			&i.Conversation.ShopID,
			&i.Conversation.LastMessageAt,
			&i.Conversation.LastMessagePreview,
			&i.Conversation.CreatedAt,
			&i.UnreadTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT c.id, c.type, c.owner_user_id, c.owner_guest_key, c.shop_id, c.last_message_at, c.last_message_preview, c.created_at, unread.total AS unread_total
FROM conversation c
LEFT JOIN participant p
    ON p.conversation_id = c.id AND p.user_id = $1
LEFT JOIN LATERAL (
    SELECT count(*) AS total
    FROM message m
    WHERE m.conversation_id = c.id
      AND m.sender_participant_id IS DISTINCT FROM p.id
      AND m.created_at > COALESCE(p.last_read_at, '-infinity'::timestamptz)
) unread ON TRUE
WHERE c.owner_user_id = $1
ORDER BY c.last_message_at DESC NULLS LAST
LIMIT $2
`

type ListConversationsForUserParams struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	PageLimit   int32       `json:"page_limit"`
}

type ListConversationsForUserRow struct {
	Conversation Conversation `json:"conversation"`
	UnreadTotal  int64        `json:"unread_total"`
}

// Inbox cua buyer. Hoi thoai chua co tin nhan nao (last_message_at NULL) xep cuoi.
//
// So chua doc tinh bang LATERAL trong CUNG mot cau, khong phai goi CountUnread cho tung
// dong: mot inbox 30 hoi thoai se thanh 31 luot di ve Neon, ma Neon nam o xa va co the
// dang ngu.
//
// p co the NULL (LEFT JOIN): hoi thoai ma nguoi xem chua co row participant. Luc do
// IS DISTINCT FROM NULL dung cho MOI tin, tuc chua doc gi ca - dung y nghia can.
func (q *Queries) ListConversationsForUser(ctx context.Context, arg ListConversationsForUserParams) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, arg.OwnerUserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.Conversation.ID,
			&i.Conversation.Type,
			&i.Conversation.OwnerUserID,
			&i.Conversation.OwnerGuestKey,
			&i.Conversation.ShopID,
			&i.Conversation.LastMessageAt,
			&i.Conversation.LastMessagePreview,
			&i.Conversation.CreatedAt,
			&i.UnreadTotal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesBefore = `-- name: ListMessagesBefore :many
SELECT id, conversation_id, sender_participant_id, body, created_at FROM message
WHERE conversation_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesBeforeParams struct {
	ConversationID string      `json:"conversation_id"`
	BeforeID       pgtype.UUID `json:"before_id"`
	PageLimit      int32       `json:"page_limit"`
}

// Phan trang keyset MOT cot nho id la UUIDv7 (sap theo thoi gian). before_id NULL =
// trang dau tien. Tra ve moi nhat truoc; caller dao nguoc de hien thi.
func (q *Queries) ListMessagesBefore(ctx context.Context, arg ListMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBefore, arg.ConversationID, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderParticipantID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
UPDATE participant SET last_read_at = $1 WHERE id = $2
`

type MarkReadParams struct {
	LastReadAt pgtype.Timestamptz `json:"last_read_at"`
	ID         string             `json:"id"`
}

func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.Exec(ctx, markRead, arg.LastReadAt, arg.ID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversation
SET last_message_at = $1, last_message_preview = $2
WHERE id = $3
`

type TouchConversationParams struct {
	LastMessageAt      pgtype.Timestamptz `json:"last_message_at"`
	LastMessagePreview *string            `json:"last_message_preview"`
	ID                 string             `json:"id"`
}

func (q *Queries) TouchConversation(ctx context.Context, arg TouchConversationParams) error {
	_, err := q.db.Exec(ctx, touchConversation, arg.LastMessageAt, arg.LastMessagePreview, arg.ID)
	return err
}
