// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package searchdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProductIndex struct {
	ProductID    string             `json:"product_id"`
	Name         string             `json:"name"`
	Slug         string             `json:"slug"`
	Description  *string            `json:"description"`
	Price        pgtype.Numeric     `json:"price"`
	ShopID       string             `json:"shop_id"`
	CategoryID   pgtype.UUID        `json:"category_id"`
	ThumbnailUrl *string            `json:"thumbnail_url"`
	Status       string             `json:"status"`
	IsHidden     bool               `json:"is_hidden"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IndexedAt    pgtype.Timestamptz `json:"indexed_at"`
	SearchVector interface{}        `json:"search_vector"`
	NameUnaccent *string            `json:"name_unaccent"`
}
