// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package searchdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSearchProducts = `-- name: CountSearchProducts :one
SELECT count(*) AS total
FROM product_index
WHERE search_vector @@ websearch_to_tsquery('simple', unaccent($1::text))
  AND status = 'active'
  AND is_hidden = false
  AND ($2::numeric IS NULL OR price >= $2::numeric)
  AND ($3::numeric IS NULL OR price <= $3::numeric)
  AND ($4::uuid IS NULL OR shop_id = $4::uuid)
  AND ($5::uuid[] IS NULL OR category_id = ANY($5::uuid[]))
`

type CountSearchProductsParams struct {
	Query       string         `json:"query"`
	MinPrice    pgtype.Numeric `json:"min_price"`
	MaxPrice    pgtype.Numeric `json:"max_price"`
	ShopID      pgtype.UUID    `json:"shop_id"`
	CategoryIds []string       `json:"category_ids"`
}

func (q *Queries) CountSearchProducts(ctx context.Context, arg CountSearchProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchProducts,
		arg.Query,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ShopID,
		arg.CategoryIds,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const searchProducts = `-- name: SearchProducts :many

SELECT
    product_id,
    ts_rank_cd(search_vector, websearch_to_tsquery('simple', unaccent($1::text))) AS rank
FROM product_index
WHERE search_vector @@ websearch_to_tsquery('simple', unaccent($1::text))
  AND status = 'active'
  AND is_hidden = false
  AND ($2::numeric IS NULL OR price >= $2::numeric)
  AND ($3::numeric IS NULL OR price <= $3::numeric)
  AND ($4::uuid IS NULL OR shop_id = $4::uuid)
  AND ($5::uuid[] IS NULL OR category_id = ANY($5::uuid[]))
ORDER BY rank DESC, product_id
LIMIT $7::int OFFSET $6::int
`

type SearchProductsParams struct {
	Query       string         `json:"query"`
	MinPrice    pgtype.Numeric `json:"min_price"`
	MaxPrice    pgtype.Numeric `json:"max_price"`
	ShopID      pgtype.UUID    `json:"shop_id"`
	CategoryIds []string       `json:"category_ids"`
	PageOffset  int32          `json:"page_offset"`
	PageLimit   int32          `json:"page_limit"`
}

type SearchProductsRow struct {
	ProductID string  `json:"product_id"`
	Rank      float32 `json:"rank"`
}

// Search product theo full-text: match websearch_to_tsquery + xep hang ts_rank_cd.
// Tra product_id + rank (Pattern B: monolith hydrate data day du tu DB chinh).
// status = 'active' (chu THUONG, ProductStatus.ACTIVE) — loai deleted/suspended.
// Cac filter nullable dung sqlc.narg: NULL = bo qua dieu kien do.
func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.Query,
		arg.MinPrice,
		arg.MaxPrice,
		arg.ShopID,
		arg.CategoryIds,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(&i.ProductID, &i.Rank); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
